### ISSUE TITLE
Error in rule build_genome

### ISSUE THREAD

**Issue by TheBorgy** [dieterich-lab/single-cell-nanopore#20]
Thank you for developing this great tool. I am trying to run the pipeline on my data. Running the test data went fine but I get the following error running my data. I was wondering if you have experience with it or can help troubleshoot it?

```
Error in rule build_genome:
    jobid: 16
    output: myresults/genome.fa
    shell:
        
    samtools view mydata/possorted_genome_bam.bam | perl -ne 'print ">",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/CB:Z:([ACGT]+).*UB:Z:([ACGT]+)/){print "CTACACGACGCTCTTCCGATCT$1$2","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' > myresults/genome.fa
    gzip -dc myresults/bk_barcodes.tsv.gz | shuf -r -n 200000 --random-source=myresults/bk_barcodes.tsv.gz | perl -ne 'print ">chr",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/([ACGT]+)/){$u="";$u.=[A,T,G,C]->[rand 4]for 1..10;print "CTACACGACGCTCTTCCGATCT$1$u","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' >> myresults/genome.fa
    samtools faidx myresults/genome.fa
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/site-packages/snakemake/executors.py", line 2156, in run_wrapper
    passed_shadow_dir,
  File "/home/FCAM/usr/single-cell-nanopore/Snakefile", line 319, in __rule_build_genome
    """
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/site-packages/snakemake/shell.py", line 176, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  samtools view mydata/possorted_genome_bam.bam | perl -ne 'print ">",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/CB:Z:([ACGT]+).*UB:Z:([ACGT]+)/){print "CTACACGACGCTCTTCCGATCT$1$2","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' > myresults/genome.fa
    gzip -dc myresults/bk_barcodes.tsv.gz | shuf -r -n 200000 --random-source=myresults/bk_barcodes.tsv.gz | perl -ne 'print ">chr",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/([ACGT]+)/){$u="";$u.=[A,T,G,C]->[rand 4]for 1..10;print "CTACACGACGCTCTTCCGATCT$1$u","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' >> myresults/genome.fa
    samtools faidx myresults/genome.fa' returned non-zero exit status 139.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/site-packages/snakemake/executors.py", line 499, in _callback
    raise ex
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/site-packages/snakemake/executors.py", line 485, in cached_or_run
    run_func(*args)
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/site-packages/snakemake/executors.py", line 2168, in run_wrapper
    ex, lineno, linemaps=linemaps, snakefile=file, show_traceback=True
snakemake.exceptions.RuleException: CalledProcessError in line 173 of /home/FCAM/usr/single-cell-nanopore/Snakefile:
Command 'set -euo pipefail;  samtools view mydata/possorted_genome_bam.bam | perl -ne 'print ">",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/CB:Z:([ACGT]+).*UB:Z:([ACGT]+)/){print "CTACACGACGCTCTTCCGATCT$1$2","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' > myresults/genome.fa
    gzip -dc myresults/bk_barcodes.tsv.gz | shuf -r -n 200000 --random-source=myresults/bk_barcodes.tsv.gz | perl -ne 'print ">chr",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/([ACGT]+)/){$u="";$u.=[A,T,G,C]->[rand 4]for 1..10;print "CTACACGACGCTCTTCCGATCT$1$u","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' >> myresults/genome.fa
    samtools faidx myresults/genome.fa' returned non-zero exit status 139.
  File "/home/FCAM/usr/single-cell-nanopore/Snakefile", line 173, in __rule_build_genome

RuleException:
CalledProcessError in line 173 of /home/FCAM/usr/single-cell-nanopore/Snakefile:
Command 'set -euo pipefail;  samtools view mydata/possorted_genome_bam.bam | perl -ne 'print ">",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/CB:Z:([ACGT]+).*UB:Z:([ACGT]+)/){print "CTACACGACGCTCTTCCGATCT$1$2","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' > myresults/genome.fa
    gzip -dc myresults/bk_barcodes.tsv.gz | shuf -r -n 200000 --random-source=myresults/bk_barcodes.tsv.gz | perl -ne 'print ">chr",++$j,"\n" if $i%25e5==25e5-1 or $j==0;if (/([ACGT]+)/){$u="";$u.=[A,T,G,C]->[rand 4]for 1..10;print "CTACACGACGCTCTTCCGATCT$1$u","T"x20,GCCTGGCTTGTTTGCAAAGGCCCTGGCCAACG,"\n";$i++}' >> myresults/genome.fa
    samtools faidx myresults/genome.fa' returned non-zero exit status 139.
  File "/home/FCAM/usr/single-cell-nanopore/Snakefile", line 173, in __rule_build_genome
  File "/home/FCAM/usr/miniconda3/envs/scNapBar/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job build_genome since they might be corrupted:
myresults/genome.fa
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/FCAM/usr/single-cell-nanopore/.snakemake/log/2022-12-15T153445.434491.snakemake.log
unlocking
removing lock
removing lock
removed all locks
```

**Comment by eboileau** [comment]
Most likely related to #17
